#
# File: config.yml | Note: Maintains the CircleCI Settings & Configurations
#

version: 2
jobs:
    build:
        docker:
            - image: circleci/android:api-26-alpha
        working_directory: ~/project
        environment:
            JVM_OPTS: -Xmx3200m
        steps:
            - checkout
            - restore_cache:
                key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
            - run:
                name: Download Forests Dependencies
                command: ./gradlew androidDependencies
            - run:
                name: Build Forests
                command: ./gradlew clean build
            - save_cache:
                key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
                paths:
                    - ~/.gradle
    test:
        docker:
            - image: circleci/android:api-26-alpha
        environment:
            JVM_OPTS: -Xmx3200m
        steps:
            - checkout
            - restore_cache:
                key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
            - run:
                name: Run Forests Unit Tests & Linting
                command: ./gradlew lint app:test
            - store_artifacts:
                path: app/build/reports
                destination: application_reports
    deploy:
        docker:
            - image: circleci/android:api-26-alpha
        steps:
            - run: echo "disabled"         
      
workflows:
    version: 2
    deployment:
        jobs:
            - build
            - test:
                requires:
                    - build
            - deploy:
                type: approval
                requires:
                    - test
                filters:
                    branches:
                        only: build
    schedules: 
        triggers:
            - schedule:
                cron: "0 0 * * *"
                filters:
                    branches:
                        only: build
        jobs:
            - build